# Generated by Django 4.2.3 on 2023-07-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Too bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "Good"),
                    (5, "Excellent"),
                ]
            ),
        ),
    ]
